#! /bin/bash

FILES=()
index=0

for i in *.jpg; do

	#echo "Adding$i"
	#echo $(($index + 1))
	FILES+=("$i")
done


for j in ${FILES[@]}; do

	((index++))

	echo "renaming... $j ... to ... jimbo-IMAGE-$index.jpg"
	echo ""
	sleep .075s

	mv "$j" "jimbo-IMAGE-$index.jpg"
done
